services:
  pubsub_listener:
    build: pubsub_listener
    container_name: pubsub_listener
    restart: unless-stopped
    environment:
      - PROJECT_ID=${PROJECT_ID}
      - SUBSCRIPTION_ID=${SUBSCRIPTION_ID}
      - CREDS_FILEPATH=${CREDS_FILEPATH}

    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/

        # Rebuild the image if dependencies change by checking uv.lock
        - action: rebuild
          path: ./uv.lock

  homelab_api:
    build: homelab_api
    container_name: homelab_api
    restart: unless-stopped
    environment:
      - MIKROTIK_HOST=${MIKROTIK_HOST}
      - MIKROTIK_HTTPS_ALLOWLIST=${MIKROTIK_HTTPS_ALLOWLIST}
      - IP_TTL=${IP_TTL}
      - ALLOWED_EMAILS=${ALLOWED_EMAILS}

    volumes:
      # Mount SSH keys for MikroTik access
      - ./secrets/id_ed25519:/root/.ssh/id_ed25519
      - ./secrets/id_ed25519.pub:/root/.ssh/id_ed25519.pub

    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/

        # Rebuild the image if dependencies change by checking uv.lock
        - action: rebuild
          path: ./uv.lock
