[private]
list:
  @just -l

[group('http')]
serve:
    caddy run


[group('init')]
init-index-file:
    rm -f index.html
    op run --no-masking --env-file op.env -- \
      uvx --from jinja2-max j2 --env -i index.html.template > index.html
